- title:      Quality you can taste
  description:  We pride ourselves for using the best tasting ingredients we can get our hands on, all for your pleasure.			
  fa-icon:      fa-utensils
  link:         

- title:      Support Local
  description:  Our ingredients are supplied by Aussie businesses in close proximity to our Byron Shire production facilities.			
  fa-icon:      fa-globe-asia
  link:         

- title:      Sustainability 
  description:  100% recyclable, responsible disposal of waste.			
  fa-icon:      fa-map-marker-alt
  link:         
